# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8000, host: 5002  # gunicorn
  config.vm.network "forwarded_port", guest: 5432, host: 5432  # postgresql

  config.vm.synced_folder ".", "/srv/www/"

  $script = <<SCRIPT
sudo apt-get update
wget -q https://get.docker.com/ -O install_docker.sh
sudo sh install_docker.sh
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get update
sudo apt-get install -y python-pip
sudo pip install -U docker-compose
SCRIPT

  config.vm.provision "shell", inline: $script

end
